// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_short_hash_ from "./routes/api/short/[hash].ts";
import * as $api_short_index from "./routes/api/short/index.ts";
import * as $index from "./routes/index.tsx";
import * as $view from "./routes/view.tsx";
import * as $CreatePastaTopbar_ui_CreatePastaTopBar from "./islands/CreatePastaTopbar/ui/CreatePastaTopBar.tsx";
import * as $Editor_ui_Editor from "./islands/Editor/ui/Editor.tsx";
import * as $ShareBottomSheet_model_pack from "./islands/ShareBottomSheet/model/pack.ts";
import * as $ShareBottomSheet_ui_ShareBottomSheet from "./islands/ShareBottomSheet/ui/ShareBottomSheet.tsx";
import * as $ViewPastaTopBar_ui_ViewPastaTopBar from "./islands/ViewPastaTopBar/ui/ViewPastaTopBar.tsx";
import * as $Viewer_ui_Viewer from "./islands/Viewer/ui/Viewer.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/short/[hash].ts": $api_short_hash_,
    "./routes/api/short/index.ts": $api_short_index,
    "./routes/index.tsx": $index,
    "./routes/view.tsx": $view,
  },
  islands: {
    "./islands/CreatePastaTopbar/ui/CreatePastaTopBar.tsx":
      $CreatePastaTopbar_ui_CreatePastaTopBar,
    "./islands/Editor/ui/Editor.tsx": $Editor_ui_Editor,
    "./islands/ShareBottomSheet/model/pack.ts": $ShareBottomSheet_model_pack,
    "./islands/ShareBottomSheet/ui/ShareBottomSheet.tsx":
      $ShareBottomSheet_ui_ShareBottomSheet,
    "./islands/ViewPastaTopBar/ui/ViewPastaTopBar.tsx":
      $ViewPastaTopBar_ui_ViewPastaTopBar,
    "./islands/Viewer/ui/Viewer.tsx": $Viewer_ui_Viewer,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
